### ISSUE TITLE
Fix > Footer 

### ISSUE THREAD

**Issue by rohitroy-github** [HeisRoy33/doctor-banner#18]
Footer is broken on quite a few place as you can see here > 

![image](https://user-images.githubusercontent.com/68563695/198680238-2312391d-5fec-476d-81f5-eb261298db28.png)

If it's relevant, assign it to me, I'll take a look at the fix !

**Comment by Nayanika-12** [comment]
please assign this task to me @HeisRoy33. I can fix the footer
